### ISSUE TITLE
Redis session locking by default in ownCloud 10.3

### ISSUE THREAD

**Issue by xoxys** [owncloud-ansible/owncloud#3]
We should configure ownCloud 10.3 to use Redis session locking by default

**Comment by xoxys** [comment]
**TODO**:

- [ ] check which php-redis version is available in OS needs to be >=4.1
- [ ] I think redis server version also needs to be > 3 (can’t find mention in release notes)
- [ ] session.save_handler = redis
- [ ] session.save_path = “tcp://ip:port/auth?password” #something like that
- [ ] redis.session.locking_enabled = 1 in php.ini
